debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.example.springboardproject: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
spring:
  profiles:
    active: local

---

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: yun
    password: thisisTESTpw!@#$
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  sql:
    init:
      mode: always
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
  thymeleaf3:
    decoupled-logic: true
  config:
    activate:
      on-profile: local

---

spring:
  datasource:
    url: jdbc:mysql://spring-board-db.cq1bi0tmzwju.ap-northeast-2.rds.amazonaws.com:3306/board?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: yun
    password: asd070312!!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  sql:
    init:
      mode: always
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
  thymeleaf3:
    decoupled-logic: true
  config:
    activate:
      on-profile: aws

